name: Main Pipeline

on:
  push:
    branches: [ "Ebtehal/githubActions" ]  # ← تم التعديل هنا!

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Choose where to deploy ✨'
        required: true
        default: 'Local'
        type: choice
        options:
          - EC2
          - Local

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Build Docker Image
      - name: Build Docker Image
        run: docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:${{ github.sha }} .

      # 2. Trivy Scan & Generate Report
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'report.html'
          exit-code: '0'  # علشان يكمل حتى لو لقى ثغرات

      # 3. Prepare Artifacts (زي ما مطلوب في الرسمة)
      - name: Prepare Artifacts
        run: |
          mkdir -p scan-dir
          echo "Nginx version: alpine" > scan-dir/nginx.txt
          mkdir -p HTML
          cp report.html HTML/report.html

      # 4. Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: |
            scan-dir/
            HTML/

      # 5. Push to Quay.io
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Push Image
        run: docker push quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:${{ github.sha }}

  deploy:
    needs: ci-cd # مش بتبدأ غير لو الـ Scan والـ Push خلصوا بنجاح
    # لو اخترنا Local هيشتغل على الـ Runner بتاعك، لو EC2 هيشتغل على GitHub hosted
    runs-on: ${{ github.event.inputs.deployment_target == 'Local' && 'self-hosted' || 'ubuntu-latest' }}
    
    steps:
      # سيناريو الـ EC2: بنستخدم SSH لرمي الأوامر
      - name: Deploying to EC2 via SSH
        if: ${{ github.event.inputs.deployment_target == 'EC2' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_TOKEN }}
            docker pull quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:latest
            docker stop girly-app || true
            docker rm girly-app || true
            docker run -d --name girly-app -p 80:80 quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:latest

      # سيناريو الـ Local: الأوامر بتنفذ مباشرة على جهازك الـ Lenovo
      - name: Deploying Locally on Runner
        if: ${{ github.event.inputs.deployment_target == 'Local' }}
        run: |
          docker login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_TOKEN }}
          docker pull quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:latest
          docker stop girly-app || true
          docker rm girly-app || true
          docker run -d --name girly-app -p 8080:80 quay.io/${{ secrets.QUAY_USERNAME }}/girly-app:latest