#!/bin/bash

# =====================================================
# Checkov Professional HTML + PDF Security Report
# =====================================================

# بنحدد المسارات بناءً على المكان اللي السكريبت شغال منه
BASE_DIR="$(pwd)"
JSON_FILE="$BASE_DIR/checkov_report.json"
HTML_REPORT="$BASE_DIR/report.html"
PDF_REPORT="$BASE_DIR/report.pdf"

# -----------------------------------------------------
# Safety check
# -----------------------------------------------------
if [ ! -f "$JSON_FILE" ]; then
  echo "❌ JSON file not found: $JSON_FILE"
  exit 1
fi

# -----------------------------------------------------
# Summary Parsing
# -----------------------------------------------------
# تأكدنا إن jq موجود في الـ pipeline
PASSED_COUNT=$(jq '[.[].summary.passed] | add' "$JSON_FILE")
FAILED_COUNT=$(jq '[.[].summary.failed] | add' "$JSON_FILE")
# لو القيم فاضية (مثلاً ملف الـ json فاضي) نخليهم أصفار
PASSED_COUNT=${PASSED_COUNT:-0}
FAILED_COUNT=${FAILED_COUNT:-0}

GENERATED_AT=$(date "+%Y-%m-%d %H:%M:%S")

# -----------------------------------------------------
# Failed rows with Severity
# -----------------------------------------------------
FAILED_ROWS=$(jq -r '
def severity:
  if .check_id | startswith("CKV2") then "Critical"
  elif .check_id | startswith("CKV_SECRET") then "Critical"
  else "High"
  end;

def severity_class:
  if .check_id | startswith("CKV2") then "badge-critical"
  elif .check_id | startswith("CKV_SECRET") then "badge-critical"
  else "badge-high"
  end;

.[] |
.results.failed_checks[]? |
"<tr>
  <td>" + (.resource // "N/A") + "</td>
  <td>" + .check_name + "</td>
  <td><span class=\"badge " + severity_class + "\">" + severity + "</span></td>
  <td><span class=\"badge badge-fail\">FAILED</span></td>
  <td><a href=\"" + (.guideline // "#") + "\" target=\"_blank\">Remediation</a></td>
</tr>"
' "$JSON_FILE")

# -----------------------------------------------------
# HTML Generation
# -----------------------------------------------------
cat <<EOF > "$HTML_REPORT"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Checkov Security Report</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
body { font-family: Inter, system-ui, sans-serif; background: #f4f6f8; margin: 0; color: #1f2937; }
.header { background: linear-gradient(135deg, #111827, #1f2937); color: white; padding: 24px 40px; }
.header h1 { margin: 0; font-size: 26px; }
.header p { margin: 6px 0 0; font-size: 14px; color: #d1d5db; }
.container { max-width: 1200px; margin: auto; padding: 40px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }
.card { background: white; border-radius: 12px; padding: 20px; box-shadow: 0 10px 25px rgba(0,0,0,0.06); }
.card .value { font-size: 34px; font-weight: bold; }
.success { color: #16a34a; } .danger { color: #dc2626; }
table { width: 100%; background: white; border-collapse: collapse; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.06); }
thead { background: #111827; color: white; }
th, td { padding: 14px 16px; text-align: left; }
tbody tr { border-bottom: 1px solid #e5e7eb; }
.badge { padding: 4px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; }
.badge-fail { background: #fee2e2; color: #b91c1c; }
.badge-critical { background: #fee2e2; color: #991b1b; }
.badge-high { background: #ffedd5; color: #9a3412; }
.footer { background: #111827; color: #9ca3af; text-align: center; padding: 18px; font-size: 13px; margin-top: 40px;}
</style>
</head>
<body>

<div class="header">
  <h1>🔐 Security Assessment Report</h1>
  <p>Generated by Checkov • $GENERATED_AT</p>
</div>

<div class="container">
  <div class="cards">
    <div class="card"><h2>Passed Checks</h2><div class="value success">$PASSED_COUNT</div></div>
    <div class="card"><h2>Failed Checks</h2><div class="value danger">$FAILED_COUNT</div></div>
  </div>

  <div class="cards" style="height: 300px">
    <div class="card"><canvas id="donutChart"></canvas></div>
    <div class="card"><canvas id="barChart"></canvas></div>
  </div>

  $(if [ "$FAILED_COUNT" -gt 0 ]; then
    echo "<table><thead><tr><th>Resource</th><th>Check</th><th>Severity</th><th>Status</th><th>Fix</th></tr></thead><tbody>$FAILED_ROWS</tbody></table>"
  else
    echo "<div style='background:#ecfdf5;color:#065f46;padding:20px;border-radius:10px;'>✅ Amazing! No security issues found.</div>"
  fi)

</div>

<div class="footer">© 2026 • Security Pipeline • Checkov</div>

<script>
const p = $PASSED_COUNT; const f = $FAILED_COUNT;
new Chart(document.getElementById('donutChart'), { type: 'doughnut', data: { labels: ['Passed', 'Failed'], datasets: [{ data: [p, f], backgroundColor: ['#22c55e', '#ef4444'] }] } });
new Chart(document.getElementById('barChart'), { type: 'bar', data: { labels: ['Passed', 'Failed'], datasets: [{ data: [p, f], backgroundColor: ['#22c55e', '#ef4444'] }] }, options: { plugins: { legend: { display: false } } } });
</script>

</body>
</html>
EOF

echo "✅ HTML report generated: $HTML_REPORT"

# -----------------------------------------------------
# PDF Export (Optional in CI if tool missing)
# -----------------------------------------------------
if command -v wkhtmltopdf &> /dev/null; then
    wkhtmltopdf "$HTML_REPORT" "$PDF_REPORT" >/dev/null 2>&1
    echo "📄 PDF report generated: $PDF_REPORT"
else
    echo "⚠️ wkhtmltopdf not found, skipping PDF generation."
fi
